stages:
  - build
  - deploy

.tag_only:
  only:
    refs:
      - tags

build:
  extends: .tag_only
  stage: build
  script:
    - .\gitlab\build.bat "${UNITY_EXE}" --buildDir "${CI_COMMIT_TAG}"
    - echo ${CI_COMMIT_TAG} > "Build\${CI_COMMIT_TAG}\version.txt"
  artifacts:
    name: "VRtist_${CI_COMMIT_TAG}"
    paths:
      - "Build/${CI_COMMIT_TAG}"
  tags:
    - unity

release:
  extends: .tag_only
  stage: deploy
  tags:
    - docker
  image: python:3
  script:
    - pip install requests
    - pip install pygithub
    - python -m zipfile -c vrtist-${CI_COMMIT_REF_NAME}.zip Build/${CI_COMMIT_TAG}/
    - python -m gitlab.create_gitlab_release vrtist-${CI_COMMIT_REF_NAME}.zip
    - python -m gitlab.create_github_release --tag ${CI_COMMIT_TAG} --name ${CI_COMMIT_TAG} --zip vrtist-${CI_COMMIT_REF_NAME}.zip

deploy:
  extends: .tag_only
  stage: deploy
  script:
    - xcopy /y/s/e/i Build\${CI_COMMIT_TAG} ${UAS_DEPLOY_FOLDER}\${CI_COMMIT_TAG}
  tags:
    - uas
